//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.11 at 12:54:48 PM IST 
//


package com.aflac.xml.masterApp.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountAndEligiblity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountAndEligiblity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="groupNumberOrGpId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="organizationName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cityOfHq" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subsidiariesAffiliates" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="certHolders" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hourPerWeekFullTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="hourPerWeekpartTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstOftheMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fullTimeOrPartTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fullTimeEligibleCoverageDuration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="partTimeEligibleCoverageDuration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fullTimeEligibleCoverageMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="partTimeEligibleCoverageMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="enrollEmployeeCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="eligibleEmployeeCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="otherRequirement" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="purposeOfApplication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="classesAddedOrRemoved" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="policyNumbers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="employerTaxNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="applicant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="applicantOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sicCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numberOrStreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physicalAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physicalNumberOrStreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physicalCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physicalState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physicalZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authorizedPersonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authorizedPersonTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contactTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="erisaPlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="planNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="churchPlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sadToBeCovered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sadNames" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountAndEligiblity", propOrder = {
    "groupNumberOrGpId",
    "effectiveDate",
    "organizationName",
    "cityOfHq",
    "subsidiariesAffiliates",
    "certHolders",
    "hourPerWeekFullTime",
    "hourPerWeekpartTime",
    "firstOftheMonth",
    "fullTimeOrPartTime",
    "fullTimeEligibleCoverageDuration",
    "partTimeEligibleCoverageDuration",
    "fullTimeEligibleCoverageMonth",
    "partTimeEligibleCoverageMonth",
    "enrollEmployeeCount",
    "eligibleEmployeeCount",
    "otherRequirement",
    "purposeOfApplication",
    "classesAddedOrRemoved",
    "policyNumbers",
    "employerTaxNumber",
    "applicant",
    "applicantOther",
    "sicCode",
    "address",
    "numberOrStreet",
    "city",
    "state",
    "zip",
    "physicalAddress",
    "physicalNumberOrStreet",
    "physicalCity",
    "physicalState",
    "physicalZip",
    "authorizedPersonName",
    "authorizedPersonTitle",
    "contactName",
    "contactTitle",
    "contactPhone",
    "contactEmail",
    "erisaPlan",
    "planNumber",
    "churchPlan",
    "sadToBeCovered",
    "sadNames"
})
public class AccountAndEligiblity {

    @XmlElement(required = true)
    protected String groupNumberOrGpId;
    @XmlElement(required = true)
    protected String effectiveDate;
    @XmlElement(required = true)
    protected String organizationName;
    @XmlElement(required = true)
    protected String cityOfHq;
    @XmlElement(required = true)
    protected String subsidiariesAffiliates;
    @XmlElement(required = true)
    protected String certHolders;
    protected String hourPerWeekFullTime;
    protected String hourPerWeekpartTime;
    protected String firstOftheMonth;
    protected String fullTimeOrPartTime;
    protected String fullTimeEligibleCoverageDuration;
    protected String partTimeEligibleCoverageDuration;
    protected String fullTimeEligibleCoverageMonth;
    protected String partTimeEligibleCoverageMonth;
    protected int enrollEmployeeCount;
    protected int eligibleEmployeeCount;
    @XmlElement(required = true)
    protected String otherRequirement;
    protected String purposeOfApplication;
    protected String classesAddedOrRemoved;
    protected String policyNumbers;
    protected String employerTaxNumber;
    protected String applicant;
    protected String applicantOther;
    protected String sicCode;
    protected String address;
    protected String numberOrStreet;
    protected String city;
    protected String state;
    protected String zip;
    protected String physicalAddress;
    protected String physicalNumberOrStreet;
    protected String physicalCity;
    protected String physicalState;
    protected String physicalZip;
    protected String authorizedPersonName;
    protected String authorizedPersonTitle;
    protected String contactName;
    protected String contactTitle;
    protected String contactPhone;
    protected String contactEmail;
    protected String erisaPlan;
    protected String planNumber;
    protected String churchPlan;
    protected String sadToBeCovered;
    protected String sadNames;

    /**
     * Gets the value of the groupNumberOrGpId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupNumberOrGpId() {
        return groupNumberOrGpId;
    }

    /**
     * Sets the value of the groupNumberOrGpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupNumberOrGpId(String value) {
        this.groupNumberOrGpId = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the organizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * Sets the value of the organizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationName(String value) {
        this.organizationName = value;
    }

    /**
     * Gets the value of the cityOfHq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityOfHq() {
        return cityOfHq;
    }

    /**
     * Sets the value of the cityOfHq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityOfHq(String value) {
        this.cityOfHq = value;
    }

    /**
     * Gets the value of the subsidiariesAffiliates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsidiariesAffiliates() {
        return subsidiariesAffiliates;
    }

    /**
     * Sets the value of the subsidiariesAffiliates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsidiariesAffiliates(String value) {
        this.subsidiariesAffiliates = value;
    }

    /**
     * Gets the value of the certHolders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertHolders() {
        return certHolders;
    }

    /**
     * Sets the value of the certHolders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertHolders(String value) {
        this.certHolders = value;
    }

    /**
     * Gets the value of the hourPerWeekFullTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHourPerWeekFullTime() {
        return hourPerWeekFullTime;
    }

    /**
     * Sets the value of the hourPerWeekFullTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHourPerWeekFullTime(String value) {
        this.hourPerWeekFullTime = value;
    }

    /**
     * Gets the value of the hourPerWeekpartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHourPerWeekpartTime() {
        return hourPerWeekpartTime;
    }

    /**
     * Sets the value of the hourPerWeekpartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHourPerWeekpartTime(String value) {
        this.hourPerWeekpartTime = value;
    }

    /**
     * Gets the value of the firstOftheMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstOftheMonth() {
        return firstOftheMonth;
    }

    /**
     * Sets the value of the firstOftheMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstOftheMonth(String value) {
        this.firstOftheMonth = value;
    }

    /**
     * Gets the value of the fullTimeOrPartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullTimeOrPartTime() {
        return fullTimeOrPartTime;
    }

    /**
     * Sets the value of the fullTimeOrPartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullTimeOrPartTime(String value) {
        this.fullTimeOrPartTime = value;
    }

    /**
     * Gets the value of the fullTimeEligibleCoverageDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullTimeEligibleCoverageDuration() {
        return fullTimeEligibleCoverageDuration;
    }

    /**
     * Sets the value of the fullTimeEligibleCoverageDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullTimeEligibleCoverageDuration(String value) {
        this.fullTimeEligibleCoverageDuration = value;
    }

    /**
     * Gets the value of the partTimeEligibleCoverageDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartTimeEligibleCoverageDuration() {
        return partTimeEligibleCoverageDuration;
    }

    /**
     * Sets the value of the partTimeEligibleCoverageDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartTimeEligibleCoverageDuration(String value) {
        this.partTimeEligibleCoverageDuration = value;
    }

    /**
     * Gets the value of the fullTimeEligibleCoverageMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullTimeEligibleCoverageMonth() {
        return fullTimeEligibleCoverageMonth;
    }

    /**
     * Sets the value of the fullTimeEligibleCoverageMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullTimeEligibleCoverageMonth(String value) {
        this.fullTimeEligibleCoverageMonth = value;
    }

    /**
     * Gets the value of the partTimeEligibleCoverageMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartTimeEligibleCoverageMonth() {
        return partTimeEligibleCoverageMonth;
    }

    /**
     * Sets the value of the partTimeEligibleCoverageMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartTimeEligibleCoverageMonth(String value) {
        this.partTimeEligibleCoverageMonth = value;
    }

    /**
     * Gets the value of the enrollEmployeeCount property.
     * 
     */
    public int getEnrollEmployeeCount() {
        return enrollEmployeeCount;
    }

    /**
     * Sets the value of the enrollEmployeeCount property.
     * 
     */
    public void setEnrollEmployeeCount(int value) {
        this.enrollEmployeeCount = value;
    }

    /**
     * Gets the value of the eligibleEmployeeCount property.
     * 
     */
    public int getEligibleEmployeeCount() {
        return eligibleEmployeeCount;
    }

    /**
     * Sets the value of the eligibleEmployeeCount property.
     * 
     */
    public void setEligibleEmployeeCount(int value) {
        this.eligibleEmployeeCount = value;
    }

    /**
     * Gets the value of the otherRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherRequirement() {
        return otherRequirement;
    }

    /**
     * Sets the value of the otherRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherRequirement(String value) {
        this.otherRequirement = value;
    }

    /**
     * Gets the value of the purposeOfApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurposeOfApplication() {
        return purposeOfApplication;
    }

    /**
     * Sets the value of the purposeOfApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurposeOfApplication(String value) {
        this.purposeOfApplication = value;
    }

    /**
     * Gets the value of the classesAddedOrRemoved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassesAddedOrRemoved() {
        return classesAddedOrRemoved;
    }

    /**
     * Sets the value of the classesAddedOrRemoved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassesAddedOrRemoved(String value) {
        this.classesAddedOrRemoved = value;
    }

    /**
     * Gets the value of the policyNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyNumbers() {
        return policyNumbers;
    }

    /**
     * Sets the value of the policyNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyNumbers(String value) {
        this.policyNumbers = value;
    }

    /**
     * Gets the value of the employerTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployerTaxNumber() {
        return employerTaxNumber;
    }

    /**
     * Sets the value of the employerTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployerTaxNumber(String value) {
        this.employerTaxNumber = value;
    }

    /**
     * Gets the value of the applicant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * Sets the value of the applicant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicant(String value) {
        this.applicant = value;
    }

    /**
     * Gets the value of the applicantOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantOther() {
        return applicantOther;
    }

    /**
     * Sets the value of the applicantOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantOther(String value) {
        this.applicantOther = value;
    }

    /**
     * Gets the value of the sicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicCode() {
        return sicCode;
    }

    /**
     * Sets the value of the sicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicCode(String value) {
        this.sicCode = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the numberOrStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOrStreet() {
        return numberOrStreet;
    }

    /**
     * Sets the value of the numberOrStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOrStreet(String value) {
        this.numberOrStreet = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the physicalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalAddress() {
        return physicalAddress;
    }

    /**
     * Sets the value of the physicalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalAddress(String value) {
        this.physicalAddress = value;
    }

    /**
     * Gets the value of the physicalNumberOrStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalNumberOrStreet() {
        return physicalNumberOrStreet;
    }

    /**
     * Sets the value of the physicalNumberOrStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalNumberOrStreet(String value) {
        this.physicalNumberOrStreet = value;
    }

    /**
     * Gets the value of the physicalCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalCity() {
        return physicalCity;
    }

    /**
     * Sets the value of the physicalCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalCity(String value) {
        this.physicalCity = value;
    }

    /**
     * Gets the value of the physicalState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalState() {
        return physicalState;
    }

    /**
     * Sets the value of the physicalState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalState(String value) {
        this.physicalState = value;
    }

    /**
     * Gets the value of the physicalZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalZip() {
        return physicalZip;
    }

    /**
     * Sets the value of the physicalZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalZip(String value) {
        this.physicalZip = value;
    }

    /**
     * Gets the value of the authorizedPersonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedPersonName() {
        return authorizedPersonName;
    }

    /**
     * Sets the value of the authorizedPersonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedPersonName(String value) {
        this.authorizedPersonName = value;
    }

    /**
     * Gets the value of the authorizedPersonTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedPersonTitle() {
        return authorizedPersonTitle;
    }

    /**
     * Sets the value of the authorizedPersonTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedPersonTitle(String value) {
        this.authorizedPersonTitle = value;
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactName(String value) {
        this.contactName = value;
    }

    /**
     * Gets the value of the contactTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactTitle() {
        return contactTitle;
    }

    /**
     * Sets the value of the contactTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactTitle(String value) {
        this.contactTitle = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the erisaPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErisaPlan() {
        return erisaPlan;
    }

    /**
     * Sets the value of the erisaPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErisaPlan(String value) {
        this.erisaPlan = value;
    }

    /**
     * Gets the value of the planNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanNumber() {
        return planNumber;
    }

    /**
     * Sets the value of the planNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanNumber(String value) {
        this.planNumber = value;
    }

    /**
     * Gets the value of the churchPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChurchPlan() {
        return churchPlan;
    }

    /**
     * Sets the value of the churchPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChurchPlan(String value) {
        this.churchPlan = value;
    }

    /**
     * Gets the value of the sadToBeCovered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSadToBeCovered() {
        return sadToBeCovered;
    }

    /**
     * Sets the value of the sadToBeCovered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSadToBeCovered(String value) {
        this.sadToBeCovered = value;
    }

    /**
     * Gets the value of the sadNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSadNames() {
        return sadNames;
    }

    /**
     * Sets the value of the sadNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSadNames(String value) {
        this.sadNames = value;
    }

}
