//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.01 at 01:09:37 PM IST 
//


package com.aflac.xml.masterApp.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for masterApp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="masterApp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MetaData" type="{}MetaData"/&gt;
 *         &lt;element name="masterAppEntityId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="situsState" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="groupType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="censusEnrollment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="eligible-series" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="formIds" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="firstSignerEmailId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="secondSignerEmailId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="formId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="formFolderLocation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="eSignatureRequired" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="forStatusUpdate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="signatureStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filenetDocumentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="masterappSentDatetime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="masterappReceivedDatetime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AccountAndEligiblity" type="{}AccountAndEligiblity"/&gt;
 *         &lt;element name="Product" type="{}Product" maxOccurs="unbounded"/&gt;
 *         &lt;element name="MasterAppReviewTable" type="{}MasterAppReviewTable"/&gt;
 *         &lt;element name="dataStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstAttachment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="secondAttachment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="signatureMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="signatureFlow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ccs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="signingDeadline" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="reminderFrequency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "masterApp", propOrder = {
    "metaData",
    "masterAppEntityId",
    "version",
    "situsState",
    "groupType",
    "censusEnrollment",
    "eligibleSeries",
    "formIds",
    "firstSignerEmailId",
    "secondSignerEmailId",
    "formId",
    "formFolderLocation",
    "eSignatureRequired",
    "contractTitle",
    "forStatusUpdate",
    "signatureStatus",
    "filenetDocumentId",
    "masterappSentDatetime",
    "masterappReceivedDatetime",
    "accountAndEligiblity",
    "product",
    "masterAppReviewTable",
    "dataStatus",
    "firstAttachment",
    "secondAttachment",
    "signatureMessage",
    "signatureFlow",
    "ccs",
    "signingDeadline",
    "reminderFrequency"
})
public class MasterApp {

    @XmlElement(name = "MetaData", required = true)
    protected MetaData metaData;
    @XmlElement(required = true)
    protected String masterAppEntityId;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected String situsState;
    @XmlElement(required = true)
    protected String groupType;
    @XmlElement(required = true)
    protected String censusEnrollment;
    @XmlElement(name = "eligible-series", required = true)
    protected String eligibleSeries;
    @XmlElement(required = true)
    protected String formIds;
    protected String firstSignerEmailId;
    protected String secondSignerEmailId;
    @XmlElement(required = true)
    protected String formId;
    @XmlElement(required = true)
    protected String formFolderLocation;
    @XmlElement(required = true)
    protected String eSignatureRequired;
    @XmlElement(required = true)
    protected String contractTitle;
    protected Boolean forStatusUpdate;
    protected String signatureStatus;
    protected String filenetDocumentId;
    protected String masterappSentDatetime;
    protected String masterappReceivedDatetime;
    @XmlElement(name = "AccountAndEligiblity", required = true)
    protected AccountAndEligiblity accountAndEligiblity;
    @XmlElement(name = "Product", required = true)
    protected List<Product> product;
    @XmlElement(name = "MasterAppReviewTable", required = true)
    protected MasterAppReviewTable masterAppReviewTable;
    protected String dataStatus;
    protected String firstAttachment;
    protected String secondAttachment;
    protected String signatureMessage;
    protected String signatureFlow;
    protected String ccs;
    protected Integer signingDeadline;
    protected String reminderFrequency;

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaData }
     *     
     */
    public MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaData }
     *     
     */
    public void setMetaData(MetaData value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the masterAppEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterAppEntityId() {
        return masterAppEntityId;
    }

    /**
     * Sets the value of the masterAppEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterAppEntityId(String value) {
        this.masterAppEntityId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the situsState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSitusState() {
        return situsState;
    }

    /**
     * Sets the value of the situsState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSitusState(String value) {
        this.situsState = value;
    }

    /**
     * Gets the value of the groupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * Sets the value of the groupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupType(String value) {
        this.groupType = value;
    }

    /**
     * Gets the value of the censusEnrollment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensusEnrollment() {
        return censusEnrollment;
    }

    /**
     * Sets the value of the censusEnrollment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensusEnrollment(String value) {
        this.censusEnrollment = value;
    }

    /**
     * Gets the value of the eligibleSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibleSeries() {
        return eligibleSeries;
    }

    /**
     * Sets the value of the eligibleSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibleSeries(String value) {
        this.eligibleSeries = value;
    }

    /**
     * Gets the value of the formIds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormIds() {
        return formIds;
    }

    /**
     * Sets the value of the formIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormIds(String value) {
        this.formIds = value;
    }

    /**
     * Gets the value of the firstSignerEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstSignerEmailId() {
        return firstSignerEmailId;
    }

    /**
     * Sets the value of the firstSignerEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstSignerEmailId(String value) {
        this.firstSignerEmailId = value;
    }

    /**
     * Gets the value of the secondSignerEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondSignerEmailId() {
        return secondSignerEmailId;
    }

    /**
     * Sets the value of the secondSignerEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondSignerEmailId(String value) {
        this.secondSignerEmailId = value;
    }

    /**
     * Gets the value of the formId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormId() {
        return formId;
    }

    /**
     * Sets the value of the formId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormId(String value) {
        this.formId = value;
    }

    /**
     * Gets the value of the formFolderLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormFolderLocation() {
        return formFolderLocation;
    }

    /**
     * Sets the value of the formFolderLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormFolderLocation(String value) {
        this.formFolderLocation = value;
    }

    /**
     * Gets the value of the eSignatureRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESignatureRequired() {
        return eSignatureRequired;
    }

    /**
     * Sets the value of the eSignatureRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESignatureRequired(String value) {
        this.eSignatureRequired = value;
    }

    /**
     * Gets the value of the contractTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractTitle() {
        return contractTitle;
    }

    /**
     * Sets the value of the contractTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractTitle(String value) {
        this.contractTitle = value;
    }

    /**
     * Gets the value of the forStatusUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForStatusUpdate() {
        return forStatusUpdate;
    }

    /**
     * Sets the value of the forStatusUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForStatusUpdate(Boolean value) {
        this.forStatusUpdate = value;
    }

    /**
     * Gets the value of the signatureStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureStatus() {
        return signatureStatus;
    }

    /**
     * Sets the value of the signatureStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureStatus(String value) {
        this.signatureStatus = value;
    }

    /**
     * Gets the value of the filenetDocumentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilenetDocumentId() {
        return filenetDocumentId;
    }

    /**
     * Sets the value of the filenetDocumentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilenetDocumentId(String value) {
        this.filenetDocumentId = value;
    }

    /**
     * Gets the value of the masterappSentDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterappSentDatetime() {
        return masterappSentDatetime;
    }

    /**
     * Sets the value of the masterappSentDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterappSentDatetime(String value) {
        this.masterappSentDatetime = value;
    }

    /**
     * Gets the value of the masterappReceivedDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterappReceivedDatetime() {
        return masterappReceivedDatetime;
    }

    /**
     * Sets the value of the masterappReceivedDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterappReceivedDatetime(String value) {
        this.masterappReceivedDatetime = value;
    }

    /**
     * Gets the value of the accountAndEligiblity property.
     * 
     * @return
     *     possible object is
     *     {@link AccountAndEligiblity }
     *     
     */
    public AccountAndEligiblity getAccountAndEligiblity() {
        return accountAndEligiblity;
    }

    /**
     * Sets the value of the accountAndEligiblity property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountAndEligiblity }
     *     
     */
    public void setAccountAndEligiblity(AccountAndEligiblity value) {
        this.accountAndEligiblity = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Product }
     * 
     * 
     */
    public List<Product> getProduct() {
        if (product == null) {
            product = new ArrayList<Product>();
        }
        return this.product;
    }

    public void setProduct(List<Product> product) {
		this.product = product;
	}
    /**
     * Gets the value of the masterAppReviewTable property.
     * 
     * @return
     *     possible object is
     *     {@link MasterAppReviewTable }
     *     
     */
    public MasterAppReviewTable getMasterAppReviewTable() {
        return masterAppReviewTable;
    }

    /**
     * Sets the value of the masterAppReviewTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterAppReviewTable }
     *     
     */
    public void setMasterAppReviewTable(MasterAppReviewTable value) {
        this.masterAppReviewTable = value;
    }

    /**
     * Gets the value of the dataStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * Sets the value of the dataStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataStatus(String value) {
        this.dataStatus = value;
    }

    /**
     * Gets the value of the firstAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstAttachment() {
        return firstAttachment;
    }

    /**
     * Sets the value of the firstAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstAttachment(String value) {
        this.firstAttachment = value;
    }

    /**
     * Gets the value of the secondAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondAttachment() {
        return secondAttachment;
    }

    /**
     * Sets the value of the secondAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondAttachment(String value) {
        this.secondAttachment = value;
    }

    /**
     * Gets the value of the signatureMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureMessage() {
        return signatureMessage;
    }

    /**
     * Sets the value of the signatureMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureMessage(String value) {
        this.signatureMessage = value;
    }

    /**
     * Gets the value of the signatureFlow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureFlow() {
        return signatureFlow;
    }

    /**
     * Sets the value of the signatureFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureFlow(String value) {
        this.signatureFlow = value;
    }

    /**
     * Gets the value of the ccs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcs() {
        return ccs;
    }

    /**
     * Sets the value of the ccs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcs(String value) {
        this.ccs = value;
    }

    /**
     * Gets the value of the signingDeadline property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSigningDeadline() {
        return signingDeadline;
    }

    /**
     * Sets the value of the signingDeadline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSigningDeadline(Integer value) {
        this.signingDeadline = value;
    }

    /**
     * Gets the value of the reminderFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReminderFrequency() {
        return reminderFrequency;
    }

    /**
     * Sets the value of the reminderFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReminderFrequency(String value) {
        this.reminderFrequency = value;
    }

}
