//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.12 at 11:15:12 AM IST 
//


package com.aflac.xml.masterApp.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productSequence" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="series" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="planLevelPremium" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="benefitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="applicationReason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="existingPolicyNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OtherApplicationReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eligibleEmployee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eligibleEmployeeClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eligibleSpouse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eligibleEmployeeExcept" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eligibleEmployeeOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="plan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="planFeatures" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="planFeaturesOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="optionalFeatures" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="optionalFeaturesOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="optionalFeaturesText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rates" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productContribution" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="employeePremium" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="employerPremium" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isReplacingGroupPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="policyOrCarrierNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="incomeReplacement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="benefitPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eliminationPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="groupPolicyState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="optionalTermlifeCoverages" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ciac" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="proposedEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="onDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="minimumNoOfEmployees" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="percentileOfEligibleEmployees" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="premiumPaid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="premiumPaymentMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="employeeCostOfInsurance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ActivelyAtWork" type="{}ActivelyAtWork" minOccurs="0"/&gt;
 *         &lt;element name="WaitingPeriodEligibility" type="{}WaitingPeriodEligibility" minOccurs="0"/&gt;
 *         &lt;element name="planYearPerInsured" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="hiEnrollEmployeeCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="premiumDue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "productName",
    "productSequence",
    "series",
    "planLevelPremium",
    "benefitType",
    "applicationReason",
    "existingPolicyNumber",
    "otherApplicationReason",
    "eligibleEmployee",
    "eligibleEmployeeClass",
    "eligibleSpouse",
    "eligibleEmployeeExcept",
    "eligibleEmployeeOther",
    "productClass",
    "plan",
    "planFeatures",
    "planFeaturesOther",
    "optionalFeatures",
    "optionalFeaturesOther",
    "optionalFeaturesText",
    "effectiveDate",
    "rates",
    "productContribution",
    "employeePremium",
    "employerPremium",
    "isReplacingGroupPolicy",
    "policyOrCarrierNumber",
    "incomeReplacement",
    "benefitPeriod",
    "eliminationPeriod",
    "groupPolicyState",
    "optionalTermlifeCoverages",
    "ciac",
    "proposedEffectiveDate",
    "onDate",
    "minimumNoOfEmployees",
    "percentileOfEligibleEmployees",
    "premiumPaid",
    "premiumPaymentMode",
    "employeeCostOfInsurance",
    "activelyAtWork",
    "waitingPeriodEligibility",
    "planYearPerInsured",
    "hiEnrollEmployeeCount",
    "premiumDue"
})
public class Product {

    @XmlElement(required = true)
    protected String productName;
    protected int productSequence;
    @XmlElement(required = true)
    protected String series;
    protected String planLevelPremium;
    protected String benefitType;
    @XmlElement(required = true)
    protected String applicationReason;
    protected String existingPolicyNumber;
    @XmlElement(name = "OtherApplicationReason")
    protected String otherApplicationReason;
    protected String eligibleEmployee;
    protected String eligibleEmployeeClass;
    protected String eligibleSpouse;
    protected String eligibleEmployeeExcept;
    protected String eligibleEmployeeOther;
    protected String productClass;
    protected String plan;
    protected List<String> planFeatures;
    protected String planFeaturesOther;
    protected List<String> optionalFeatures;
    protected String optionalFeaturesOther;
    protected String optionalFeaturesText;
    @XmlElement(required = true)
    protected String effectiveDate;
    @XmlElement(required = true)
    protected String rates;
    @XmlElement(required = true)
    protected String productContribution;
    @XmlElement(required = true)
    protected String employeePremium;
    @XmlElement(required = true)
    protected String employerPremium;
    protected String isReplacingGroupPolicy;
    protected String policyOrCarrierNumber;
    protected String incomeReplacement;
    protected String benefitPeriod;
    protected String eliminationPeriod;
    protected String groupPolicyState;
    protected String optionalTermlifeCoverages;
    protected String ciac;
    protected String proposedEffectiveDate;
    protected String onDate;
    protected String minimumNoOfEmployees;
    protected String percentileOfEligibleEmployees;
    protected String premiumPaid;
    protected String premiumPaymentMode;
    protected String employeeCostOfInsurance;
    @XmlElement(name = "ActivelyAtWork")
    protected ActivelyAtWork activelyAtWork;
    @XmlElement(name = "WaitingPeriodEligibility")
    protected WaitingPeriodEligibility waitingPeriodEligibility;
    protected String planYearPerInsured;
    protected Integer hiEnrollEmployeeCount;
    protected String premiumDue;

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productSequence property.
     * 
     */
    public int getProductSequence() {
        return productSequence;
    }

    /**
     * Sets the value of the productSequence property.
     * 
     */
    public void setProductSequence(int value) {
        this.productSequence = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeries() {
        return series;
    }

    /**
     * Sets the value of the series property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeries(String value) {
        this.series = value;
    }

    /**
     * Gets the value of the planLevelPremium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanLevelPremium() {
        return planLevelPremium;
    }

    /**
     * Sets the value of the planLevelPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanLevelPremium(String value) {
        this.planLevelPremium = value;
    }

    /**
     * Gets the value of the benefitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitType() {
        return benefitType;
    }

    /**
     * Sets the value of the benefitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitType(String value) {
        this.benefitType = value;
    }

    /**
     * Gets the value of the applicationReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationReason() {
        return applicationReason;
    }

    /**
     * Sets the value of the applicationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationReason(String value) {
        this.applicationReason = value;
    }

    /**
     * Gets the value of the existingPolicyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistingPolicyNumber() {
        return existingPolicyNumber;
    }

    /**
     * Sets the value of the existingPolicyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistingPolicyNumber(String value) {
        this.existingPolicyNumber = value;
    }

    /**
     * Gets the value of the otherApplicationReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherApplicationReason() {
        return otherApplicationReason;
    }

    /**
     * Sets the value of the otherApplicationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherApplicationReason(String value) {
        this.otherApplicationReason = value;
    }

    /**
     * Gets the value of the eligibleEmployee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibleEmployee() {
        return eligibleEmployee;
    }

    /**
     * Sets the value of the eligibleEmployee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibleEmployee(String value) {
        this.eligibleEmployee = value;
    }

    /**
     * Gets the value of the eligibleEmployeeClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibleEmployeeClass() {
        return eligibleEmployeeClass;
    }

    /**
     * Sets the value of the eligibleEmployeeClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibleEmployeeClass(String value) {
        this.eligibleEmployeeClass = value;
    }

    /**
     * Gets the value of the eligibleSpouse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibleSpouse() {
        return eligibleSpouse;
    }

    /**
     * Sets the value of the eligibleSpouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibleSpouse(String value) {
        this.eligibleSpouse = value;
    }

    /**
     * Gets the value of the eligibleEmployeeExcept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibleEmployeeExcept() {
        return eligibleEmployeeExcept;
    }

    /**
     * Sets the value of the eligibleEmployeeExcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibleEmployeeExcept(String value) {
        this.eligibleEmployeeExcept = value;
    }

    /**
     * Gets the value of the eligibleEmployeeOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibleEmployeeOther() {
        return eligibleEmployeeOther;
    }

    /**
     * Sets the value of the eligibleEmployeeOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibleEmployeeOther(String value) {
        this.eligibleEmployeeOther = value;
    }

    /**
     * Gets the value of the productClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the productClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClass(String value) {
        this.productClass = value;
    }

    /**
     * Gets the value of the plan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlan() {
        return plan;
    }

    /**
     * Sets the value of the plan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlan(String value) {
        this.plan = value;
    }

    /**
     * Gets the value of the planFeatures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planFeatures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanFeatures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlanFeatures() {
        if (planFeatures == null) {
            planFeatures = new ArrayList<String>();
        }
        return this.planFeatures;
    }
    
    public void setPlanFeatures(List<String> planFeatures) {
		this.planFeatures = planFeatures;
	}

	/**
     * Gets the value of the planFeaturesOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanFeaturesOther() {
        return planFeaturesOther;
    }

    /**
     * Sets the value of the planFeaturesOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanFeaturesOther(String value) {
        this.planFeaturesOther = value;
    }

    /**
     * Gets the value of the optionalFeatures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionalFeatures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionalFeatures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOptionalFeatures() {
        if (optionalFeatures == null) {
            optionalFeatures = new ArrayList<String>();
        }
        return this.optionalFeatures;
    }
    
    public void setOptionalFeatures(List<String> optionalFeatures) {
		this.optionalFeatures = optionalFeatures;
	}

	/**
     * Gets the value of the optionalFeaturesOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalFeaturesOther() {
        return optionalFeaturesOther;
    }

    /**
     * Sets the value of the optionalFeaturesOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalFeaturesOther(String value) {
        this.optionalFeaturesOther = value;
    }

    /**
     * Gets the value of the optionalFeaturesText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalFeaturesText() {
        return optionalFeaturesText;
    }

    /**
     * Sets the value of the optionalFeaturesText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalFeaturesText(String value) {
        this.optionalFeaturesText = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the rates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRates() {
        return rates;
    }

    /**
     * Sets the value of the rates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRates(String value) {
        this.rates = value;
    }

    /**
     * Gets the value of the productContribution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductContribution() {
        return productContribution;
    }

    /**
     * Sets the value of the productContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductContribution(String value) {
        this.productContribution = value;
    }

    /**
     * Gets the value of the employeePremium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeePremium() {
        return employeePremium;
    }

    /**
     * Sets the value of the employeePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeePremium(String value) {
        this.employeePremium = value;
    }

    /**
     * Gets the value of the employerPremium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployerPremium() {
        return employerPremium;
    }

    /**
     * Sets the value of the employerPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployerPremium(String value) {
        this.employerPremium = value;
    }

    /**
     * Gets the value of the isReplacingGroupPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsReplacingGroupPolicy() {
        return isReplacingGroupPolicy;
    }

    /**
     * Sets the value of the isReplacingGroupPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsReplacingGroupPolicy(String value) {
        this.isReplacingGroupPolicy = value;
    }

    /**
     * Gets the value of the policyOrCarrierNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyOrCarrierNumber() {
        return policyOrCarrierNumber;
    }

    /**
     * Sets the value of the policyOrCarrierNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyOrCarrierNumber(String value) {
        this.policyOrCarrierNumber = value;
    }

    /**
     * Gets the value of the incomeReplacement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeReplacement() {
        return incomeReplacement;
    }

    /**
     * Sets the value of the incomeReplacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeReplacement(String value) {
        this.incomeReplacement = value;
    }

    /**
     * Gets the value of the benefitPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitPeriod() {
        return benefitPeriod;
    }

    /**
     * Sets the value of the benefitPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitPeriod(String value) {
        this.benefitPeriod = value;
    }

    /**
     * Gets the value of the eliminationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEliminationPeriod() {
        return eliminationPeriod;
    }

    /**
     * Sets the value of the eliminationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEliminationPeriod(String value) {
        this.eliminationPeriod = value;
    }

    /**
     * Gets the value of the groupPolicyState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupPolicyState() {
        return groupPolicyState;
    }

    /**
     * Sets the value of the groupPolicyState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupPolicyState(String value) {
        this.groupPolicyState = value;
    }

    /**
     * Gets the value of the optionalTermlifeCoverages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalTermlifeCoverages() {
        return optionalTermlifeCoverages;
    }

    /**
     * Sets the value of the optionalTermlifeCoverages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalTermlifeCoverages(String value) {
        this.optionalTermlifeCoverages = value;
    }

    /**
     * Gets the value of the ciac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiac() {
        return ciac;
    }

    /**
     * Sets the value of the ciac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiac(String value) {
        this.ciac = value;
    }

    /**
     * Gets the value of the proposedEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProposedEffectiveDate() {
        return proposedEffectiveDate;
    }

    /**
     * Sets the value of the proposedEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProposedEffectiveDate(String value) {
        this.proposedEffectiveDate = value;
    }

    /**
     * Gets the value of the onDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnDate() {
        return onDate;
    }

    /**
     * Sets the value of the onDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnDate(String value) {
        this.onDate = value;
    }

    /**
     * Gets the value of the minimumNoOfEmployees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumNoOfEmployees() {
        return minimumNoOfEmployees;
    }

    /**
     * Sets the value of the minimumNoOfEmployees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumNoOfEmployees(String value) {
        this.minimumNoOfEmployees = value;
    }

    /**
     * Gets the value of the percentileOfEligibleEmployees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentileOfEligibleEmployees() {
        return percentileOfEligibleEmployees;
    }

    /**
     * Sets the value of the percentileOfEligibleEmployees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentileOfEligibleEmployees(String value) {
        this.percentileOfEligibleEmployees = value;
    }

    /**
     * Gets the value of the premiumPaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremiumPaid() {
        return premiumPaid;
    }

    /**
     * Sets the value of the premiumPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremiumPaid(String value) {
        this.premiumPaid = value;
    }

    /**
     * Gets the value of the premiumPaymentMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremiumPaymentMode() {
        return premiumPaymentMode;
    }

    /**
     * Sets the value of the premiumPaymentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremiumPaymentMode(String value) {
        this.premiumPaymentMode = value;
    }

    /**
     * Gets the value of the employeeCostOfInsurance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeCostOfInsurance() {
        return employeeCostOfInsurance;
    }

    /**
     * Sets the value of the employeeCostOfInsurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeCostOfInsurance(String value) {
        this.employeeCostOfInsurance = value;
    }

    /**
     * Gets the value of the activelyAtWork property.
     * 
     * @return
     *     possible object is
     *     {@link ActivelyAtWork }
     *     
     */
    public ActivelyAtWork getActivelyAtWork() {
        return activelyAtWork;
    }

    /**
     * Sets the value of the activelyAtWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivelyAtWork }
     *     
     */
    public void setActivelyAtWork(ActivelyAtWork value) {
        this.activelyAtWork = value;
    }

    /**
     * Gets the value of the waitingPeriodEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link WaitingPeriodEligibility }
     *     
     */
    public WaitingPeriodEligibility getWaitingPeriodEligibility() {
        return waitingPeriodEligibility;
    }

    /**
     * Sets the value of the waitingPeriodEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaitingPeriodEligibility }
     *     
     */
    public void setWaitingPeriodEligibility(WaitingPeriodEligibility value) {
        this.waitingPeriodEligibility = value;
    }

    /**
     * Gets the value of the planYearPerInsured property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanYearPerInsured() {
        return planYearPerInsured;
    }

    /**
     * Sets the value of the planYearPerInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanYearPerInsured(String value) {
        this.planYearPerInsured = value;
    }

    /**
     * Gets the value of the hiEnrollEmployeeCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHiEnrollEmployeeCount() {
        return hiEnrollEmployeeCount;
    }

    /**
     * Sets the value of the hiEnrollEmployeeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHiEnrollEmployeeCount(Integer value) {
        this.hiEnrollEmployeeCount = value;
    }

    /**
     * Gets the value of the premiumDue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremiumDue() {
        return premiumDue;
    }

    /**
     * Sets the value of the premiumDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremiumDue(String value) {
        this.premiumDue = value;
    }

}
