//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.17 at 03:23:26 PM IST 
//


package com.aflac.xml.casebuilderProducts.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for amountOffered complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amountOffered"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="increments" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="maximumAmtElect" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="minimumAmtElect" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="guaranteedIssueMaximum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amountOffered", propOrder = {
    "increments",
    "maximumAmtElect",
    "minimumAmtElect",
    "guaranteedIssueMaximum"
})
public class AmountOffered {

    protected int increments;
    protected int maximumAmtElect;
    protected int minimumAmtElect;
    protected int guaranteedIssueMaximum;

    /**
     * Gets the value of the increments property.
     * 
     */
    public int getIncrements() {
        return increments;
    }

    /**
     * Sets the value of the increments property.
     * 
     */
    public void setIncrements(int value) {
        this.increments = value;
    }

    /**
     * Gets the value of the maximumAmtElect property.
     * 
     */
    public int getMaximumAmtElect() {
        return maximumAmtElect;
    }

    /**
     * Sets the value of the maximumAmtElect property.
     * 
     */
    public void setMaximumAmtElect(int value) {
        this.maximumAmtElect = value;
    }

    /**
     * Gets the value of the minimumAmtElect property.
     * 
     */
    public int getMinimumAmtElect() {
        return minimumAmtElect;
    }

    /**
     * Sets the value of the minimumAmtElect property.
     * 
     */
    public void setMinimumAmtElect(int value) {
        this.minimumAmtElect = value;
    }

    /**
     * Gets the value of the guaranteedIssueMaximum property.
     * 
     */
    public int getGuaranteedIssueMaximum() {
        return guaranteedIssueMaximum;
    }

    /**
     * Sets the value of the guaranteedIssueMaximum property.
     * 
     */
    public void setGuaranteedIssueMaximum(int value) {
        this.guaranteedIssueMaximum = value;
    }

}
