//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.31 at 07:52:07 PM IST 
//


package com.aflac.xml.casebuilderProducts.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aflac.xml.casebuilderProducts.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CaseBuilderForm_QNAME = new QName("", "caseBuilderForm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aflac.xml.casebuilderProducts.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CaseBuilderForm }
     * 
     */
    public CaseBuilderForm createCaseBuilderForm() {
        return new CaseBuilderForm();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link AccountInformation }
     * 
     */
    public AccountInformation createAccountInformation() {
        return new AccountInformation();
    }

    /**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link AmountOffered }
     * 
     */
    public AmountOffered createAmountOffered() {
        return new AmountOffered();
    }

    /**
     * Create an instance of {@link EmployeeAmountOffered }
     * 
     */
    public EmployeeAmountOffered createEmployeeAmountOffered() {
        return new EmployeeAmountOffered();
    }

    /**
     * Create an instance of {@link SpouseAmountOffered }
     * 
     */
    public SpouseAmountOffered createSpouseAmountOffered() {
        return new SpouseAmountOffered();
    }

    /**
     * Create an instance of {@link ChildAmountOffered }
     * 
     */
    public ChildAmountOffered createChildAmountOffered() {
        return new ChildAmountOffered();
    }

    /**
     * Create an instance of {@link Tobacco }
     * 
     */
    public Tobacco createTobacco() {
        return new Tobacco();
    }

    /**
     * Create an instance of {@link TdiStateAmountOffered }
     * 
     */
    public TdiStateAmountOffered createTdiStateAmountOffered() {
        return new TdiStateAmountOffered();
    }

    /**
     * Create an instance of {@link ChildTermAmountOffered }
     * 
     */
    public ChildTermAmountOffered createChildTermAmountOffered() {
        return new ChildTermAmountOffered();
    }

    /**
     * Create an instance of {@link ChildIndividualAmountOffered }
     * 
     */
    public ChildIndividualAmountOffered createChildIndividualAmountOffered() {
        return new ChildIndividualAmountOffered();
    }

    /**
     * Create an instance of {@link InitialEnrollment }
     * 
     */
    public InitialEnrollment createInitialEnrollment() {
        return new InitialEnrollment();
    }

    /**
     * Create an instance of {@link Questions }
     * 
     */
    public Questions createQuestions() {
        return new Questions();
    }

    /**
     * Create an instance of {@link Affirmations }
     * 
     */
    public Affirmations createAffirmations() {
        return new Affirmations();
    }

    /**
     * Create an instance of {@link Disclosures }
     * 
     */
    public Disclosures createDisclosures() {
        return new Disclosures();
    }

    /**
     * Create an instance of {@link HealthQuestions }
     * 
     */
    public HealthQuestions createHealthQuestions() {
        return new HealthQuestions();
    }

    /**
     * Create an instance of {@link FileSubmission }
     * 
     */
    public FileSubmission createFileSubmission() {
        return new FileSubmission();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Locations }
     * 
     */
    public Locations createLocations() {
        return new Locations();
    }

    /**
     * Create an instance of {@link EeBenefitAmounts }
     * 
     */
    public EeBenefitAmounts createEeBenefitAmounts() {
        return new EeBenefitAmounts();
    }

    /**
     * Create an instance of {@link SpBenefitAmounts }
     * 
     */
    public SpBenefitAmounts createSpBenefitAmounts() {
        return new SpBenefitAmounts();
    }

    /**
     * Create an instance of {@link TdiStatesBenefitAmounts }
     * 
     */
    public TdiStatesBenefitAmounts createTdiStatesBenefitAmounts() {
        return new TdiStatesBenefitAmounts();
    }

    /**
     * Create an instance of {@link ChIndividualPolicyBenefitAmounts }
     * 
     */
    public ChIndividualPolicyBenefitAmounts createChIndividualPolicyBenefitAmounts() {
        return new ChIndividualPolicyBenefitAmounts();
    }

    /**
     * Create an instance of {@link ChBenefitAmounts }
     * 
     */
    public ChBenefitAmounts createChBenefitAmounts() {
        return new ChBenefitAmounts();
    }

    /**
     * Create an instance of {@link BenefitAmount }
     * 
     */
    public BenefitAmount createBenefitAmount() {
        return new BenefitAmount();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaseBuilderForm }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CaseBuilderForm }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "caseBuilderForm")
    public JAXBElement<CaseBuilderForm> createCaseBuilderForm(CaseBuilderForm value) {
        return new JAXBElement<CaseBuilderForm>(_CaseBuilderForm_QNAME, CaseBuilderForm.class, null, value);
    }

}
