//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.21 at 01:31:52 PM IST 
//


package com.aflac.xml.casebuilderProducts.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="planName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="planLevel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="series" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="coverageLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="applicationNumber" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="brochuresType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="diHoursWorkedPerWeek" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="employeeIssueAge" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="spouseIssueAge" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="childIssueAge" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="employeeTerminationAge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="spouseTerminationAge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="childTerminationAge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="participationRequirement" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="acceleratedDeathBenefitOffered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="hireDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="healthQueReq" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="platformDriven" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ageCalculated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ageCalculation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="issueAgeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="employeeAmountOffered" type="{}employeeAmountOffered" minOccurs="0"/&gt;
 *         &lt;element name="spouseAmountOffered" type="{}spouseAmountOffered" minOccurs="0"/&gt;
 *         &lt;element name="childAmountOffered" type="{}childAmountOffered" minOccurs="0"/&gt;
 *         &lt;element name="TdiStateAmountOffered" type="{}TdiStateAmountOffered" minOccurs="0"/&gt;
 *         &lt;element name="childIndividualAmountOffered" type="{}childIndividualAmountOffered" minOccurs="0"/&gt;
 *         &lt;element name="childTermAmountOffered" type="{}childTermAmountOffered" minOccurs="0"/&gt;
 *         &lt;element name="eeBenefitAmounts" type="{}eeBenefitAmounts" minOccurs="0"/&gt;
 *         &lt;element name="spBenefitAmounts" type="{}spBenefitAmounts" minOccurs="0"/&gt;
 *         &lt;element name="tdiStatesBenefitAmounts" type="{}tdiStatesBenefitAmounts" minOccurs="0"/&gt;
 *         &lt;element name="chIndividualPolicyBenefitAmounts" type="{}chIndividualPolicyBenefitAmounts" minOccurs="0"/&gt;
 *         &lt;element name="chBenefitAmounts" type="{}chBenefitAmounts" minOccurs="0"/&gt;
 *         &lt;element name="benefitAmountPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="hundredPercentGuranteed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eligibleEmployeeGuaranteedIssue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="initialEnrollment" type="{}initialEnrollment" minOccurs="0"/&gt;
 *         &lt;element name="benefitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="benefitPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eliminationPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="optionalRider" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="progressiveRider" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tobacco" type="{}tobacco" minOccurs="0"/&gt;
 *         &lt;element name="questions" type="{}questions" minOccurs="0"/&gt;
 *         &lt;element name="affirmations" type="{}affirmations" minOccurs="0"/&gt;
 *         &lt;element name="disclosures" type="{}disclosures" minOccurs="0"/&gt;
 *         &lt;element name="healthQuestions" type="{}healthQuestions" minOccurs="0"/&gt;
 *         &lt;element name="otherInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isChildCoverageOffered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isChildTermlifeRiderOffered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isUniqueIncrementsUtilized" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="childCoverageOffered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="benefitAmountDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isProductAro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product", propOrder = {
    "productName",
    "productId",
    "planName",
    "planLevel",
    "series",
    "coverageLevel",
    "applicationNumber",
    "brochuresType",
    "taxType",
    "diHoursWorkedPerWeek",
    "employeeIssueAge",
    "spouseIssueAge",
    "childIssueAge",
    "employeeTerminationAge",
    "spouseTerminationAge",
    "childTerminationAge",
    "participationRequirement",
    "acceleratedDeathBenefitOffered",
    "hireDate",
    "productDescription",
    "healthQueReq",
    "platformDriven",
    "ageCalculated",
    "ageCalculation",
    "issueAgeType",
    "employeeAmountOffered",
    "spouseAmountOffered",
    "childAmountOffered",
    "tdiStateAmountOffered",
    "childIndividualAmountOffered",
    "childTermAmountOffered",
    "eeBenefitAmounts",
    "spBenefitAmounts",
    "tdiStatesBenefitAmounts",
    "chIndividualPolicyBenefitAmounts",
    "chBenefitAmounts",
    "benefitAmountPercentage",
    "hundredPercentGuranteed",
    "eligibleEmployeeGuaranteedIssue",
    "initialEnrollment",
    "benefitType",
    "benefitPeriod",
    "eliminationPeriod",
    "term",
    "optionalRider",
    "progressiveRider",
    "tobacco",
    "questions",
    "affirmations",
    "disclosures",
    "healthQuestions",
    "otherInstructions",
    "isChildCoverageOffered",
    "isChildTermlifeRiderOffered",
    "isUniqueIncrementsUtilized",
    "childCoverageOffered",
    "benefitAmountDescription",
    "isProductAro"
})
public class Product {

    @XmlElement(required = true)
    protected String productName;
    @XmlElement(required = true)
    protected String productId;
    @XmlElement(required = true)
    protected String planName;
    @XmlElement(required = true)
    protected String planLevel;
    @XmlElement(required = true)
    protected String series;
    protected String coverageLevel;
    protected String applicationNumber;
    protected String brochuresType;
    @XmlElement(required = true)
    protected String taxType;
    protected String diHoursWorkedPerWeek;
    @XmlElement(required = true)
    protected String employeeIssueAge;
    @XmlElement(required = true)
    protected String spouseIssueAge;
    @XmlElement(required = true)
    protected String childIssueAge;
    protected String employeeTerminationAge;
    protected String spouseTerminationAge;
    protected String childTerminationAge;
    protected String participationRequirement;
    protected String acceleratedDeathBenefitOffered;
    @XmlElement(required = true)
    protected String hireDate;
    protected String productDescription;
    protected String healthQueReq;
    protected String platformDriven;
    protected String ageCalculated;
    protected String ageCalculation;
    protected String issueAgeType;
    protected EmployeeAmountOffered employeeAmountOffered;
    protected SpouseAmountOffered spouseAmountOffered;
    protected ChildAmountOffered childAmountOffered;
    @XmlElement(name = "TdiStateAmountOffered")
    protected TdiStateAmountOffered tdiStateAmountOffered;
    protected ChildIndividualAmountOffered childIndividualAmountOffered;
    protected ChildTermAmountOffered childTermAmountOffered;
    protected EeBenefitAmounts eeBenefitAmounts;
    protected SpBenefitAmounts spBenefitAmounts;
    protected TdiStatesBenefitAmounts tdiStatesBenefitAmounts;
    protected ChIndividualPolicyBenefitAmounts chIndividualPolicyBenefitAmounts;
    protected ChBenefitAmounts chBenefitAmounts;
    protected String benefitAmountPercentage;
    protected String hundredPercentGuranteed;
    protected String eligibleEmployeeGuaranteedIssue;
    protected InitialEnrollment initialEnrollment;
    protected String benefitType;
    protected String benefitPeriod;
    protected String eliminationPeriod;
    protected String term;
    protected String optionalRider;
    protected String progressiveRider;
    protected Tobacco tobacco;
    protected Questions questions;
    protected Affirmations affirmations;
    protected Disclosures disclosures;
    protected HealthQuestions healthQuestions;
    protected String otherInstructions;
    protected String isChildCoverageOffered;
    protected String isChildTermlifeRiderOffered;
    protected String isUniqueIncrementsUtilized;
    protected String childCoverageOffered;
    protected String benefitAmountDescription;
    protected String isProductAro;

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the planName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * Sets the value of the planName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanName(String value) {
        this.planName = value;
    }

    /**
     * Gets the value of the planLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanLevel() {
        return planLevel;
    }

    /**
     * Sets the value of the planLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanLevel(String value) {
        this.planLevel = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeries() {
        return series;
    }

    /**
     * Sets the value of the series property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeries(String value) {
        this.series = value;
    }

    /**
     * Gets the value of the coverageLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageLevel() {
        return coverageLevel;
    }

    /**
     * Sets the value of the coverageLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageLevel(String value) {
        this.coverageLevel = value;
    }

    /**
     * Gets the value of the applicationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * Sets the value of the applicationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationNumber(String value) {
        this.applicationNumber = value;
    }

    /**
     * Gets the value of the brochuresType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrochuresType() {
        return brochuresType;
    }

    /**
     * Sets the value of the brochuresType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrochuresType(String value) {
        this.brochuresType = value;
    }

    /**
     * Gets the value of the taxType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxType() {
        return taxType;
    }

    /**
     * Sets the value of the taxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxType(String value) {
        this.taxType = value;
    }

    /**
     * Gets the value of the diHoursWorkedPerWeek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiHoursWorkedPerWeek() {
        return diHoursWorkedPerWeek;
    }

    /**
     * Sets the value of the diHoursWorkedPerWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiHoursWorkedPerWeek(String value) {
        this.diHoursWorkedPerWeek = value;
    }

    /**
     * Gets the value of the employeeIssueAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeIssueAge() {
        return employeeIssueAge;
    }

    /**
     * Sets the value of the employeeIssueAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeIssueAge(String value) {
        this.employeeIssueAge = value;
    }

    /**
     * Gets the value of the spouseIssueAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpouseIssueAge() {
        return spouseIssueAge;
    }

    /**
     * Sets the value of the spouseIssueAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpouseIssueAge(String value) {
        this.spouseIssueAge = value;
    }

    /**
     * Gets the value of the childIssueAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildIssueAge() {
        return childIssueAge;
    }

    /**
     * Sets the value of the childIssueAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildIssueAge(String value) {
        this.childIssueAge = value;
    }

    /**
     * Gets the value of the employeeTerminationAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeTerminationAge() {
        return employeeTerminationAge;
    }

    /**
     * Sets the value of the employeeTerminationAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeTerminationAge(String value) {
        this.employeeTerminationAge = value;
    }

    /**
     * Gets the value of the spouseTerminationAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpouseTerminationAge() {
        return spouseTerminationAge;
    }

    /**
     * Sets the value of the spouseTerminationAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpouseTerminationAge(String value) {
        this.spouseTerminationAge = value;
    }

    /**
     * Gets the value of the childTerminationAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildTerminationAge() {
        return childTerminationAge;
    }

    /**
     * Sets the value of the childTerminationAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildTerminationAge(String value) {
        this.childTerminationAge = value;
    }

    /**
     * Gets the value of the participationRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipationRequirement() {
        return participationRequirement;
    }

    /**
     * Sets the value of the participationRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipationRequirement(String value) {
        this.participationRequirement = value;
    }

    /**
     * Gets the value of the acceleratedDeathBenefitOffered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceleratedDeathBenefitOffered() {
        return acceleratedDeathBenefitOffered;
    }

    /**
     * Sets the value of the acceleratedDeathBenefitOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceleratedDeathBenefitOffered(String value) {
        this.acceleratedDeathBenefitOffered = value;
    }

    /**
     * Gets the value of the hireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHireDate() {
        return hireDate;
    }

    /**
     * Sets the value of the hireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHireDate(String value) {
        this.hireDate = value;
    }

    /**
     * Gets the value of the productDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * Sets the value of the productDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDescription(String value) {
        this.productDescription = value;
    }

    /**
     * Gets the value of the healthQueReq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthQueReq() {
        return healthQueReq;
    }

    /**
     * Sets the value of the healthQueReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthQueReq(String value) {
        this.healthQueReq = value;
    }

    /**
     * Gets the value of the platformDriven property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformDriven() {
        return platformDriven;
    }

    /**
     * Sets the value of the platformDriven property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformDriven(String value) {
        this.platformDriven = value;
    }

    /**
     * Gets the value of the ageCalculated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeCalculated() {
        return ageCalculated;
    }

    /**
     * Sets the value of the ageCalculated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeCalculated(String value) {
        this.ageCalculated = value;
    }

    /**
     * Gets the value of the ageCalculation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeCalculation() {
        return ageCalculation;
    }

    /**
     * Sets the value of the ageCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeCalculation(String value) {
        this.ageCalculation = value;
    }

    /**
     * Gets the value of the issueAgeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueAgeType() {
        return issueAgeType;
    }

    /**
     * Sets the value of the issueAgeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueAgeType(String value) {
        this.issueAgeType = value;
    }

    /**
     * Gets the value of the employeeAmountOffered property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeAmountOffered }
     *     
     */
    public EmployeeAmountOffered getEmployeeAmountOffered() {
        return employeeAmountOffered;
    }

    /**
     * Sets the value of the employeeAmountOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeAmountOffered }
     *     
     */
    public void setEmployeeAmountOffered(EmployeeAmountOffered value) {
        this.employeeAmountOffered = value;
    }

    /**
     * Gets the value of the spouseAmountOffered property.
     * 
     * @return
     *     possible object is
     *     {@link SpouseAmountOffered }
     *     
     */
    public SpouseAmountOffered getSpouseAmountOffered() {
        return spouseAmountOffered;
    }

    /**
     * Sets the value of the spouseAmountOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpouseAmountOffered }
     *     
     */
    public void setSpouseAmountOffered(SpouseAmountOffered value) {
        this.spouseAmountOffered = value;
    }

    /**
     * Gets the value of the childAmountOffered property.
     * 
     * @return
     *     possible object is
     *     {@link ChildAmountOffered }
     *     
     */
    public ChildAmountOffered getChildAmountOffered() {
        return childAmountOffered;
    }

    /**
     * Sets the value of the childAmountOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildAmountOffered }
     *     
     */
    public void setChildAmountOffered(ChildAmountOffered value) {
        this.childAmountOffered = value;
    }

    /**
     * Gets the value of the tdiStateAmountOffered property.
     * 
     * @return
     *     possible object is
     *     {@link TdiStateAmountOffered }
     *     
     */
    public TdiStateAmountOffered getTdiStateAmountOffered() {
        return tdiStateAmountOffered;
    }

    /**
     * Sets the value of the tdiStateAmountOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link TdiStateAmountOffered }
     *     
     */
    public void setTdiStateAmountOffered(TdiStateAmountOffered value) {
        this.tdiStateAmountOffered = value;
    }

    /**
     * Gets the value of the childIndividualAmountOffered property.
     * 
     * @return
     *     possible object is
     *     {@link ChildIndividualAmountOffered }
     *     
     */
    public ChildIndividualAmountOffered getChildIndividualAmountOffered() {
        return childIndividualAmountOffered;
    }

    /**
     * Sets the value of the childIndividualAmountOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildIndividualAmountOffered }
     *     
     */
    public void setChildIndividualAmountOffered(ChildIndividualAmountOffered value) {
        this.childIndividualAmountOffered = value;
    }

    /**
     * Gets the value of the childTermAmountOffered property.
     * 
     * @return
     *     possible object is
     *     {@link ChildTermAmountOffered }
     *     
     */
    public ChildTermAmountOffered getChildTermAmountOffered() {
        return childTermAmountOffered;
    }

    /**
     * Sets the value of the childTermAmountOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildTermAmountOffered }
     *     
     */
    public void setChildTermAmountOffered(ChildTermAmountOffered value) {
        this.childTermAmountOffered = value;
    }

    /**
     * Gets the value of the eeBenefitAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link EeBenefitAmounts }
     *     
     */
    public EeBenefitAmounts getEeBenefitAmounts() {
        return eeBenefitAmounts;
    }

    /**
     * Sets the value of the eeBenefitAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link EeBenefitAmounts }
     *     
     */
    public void setEeBenefitAmounts(EeBenefitAmounts value) {
        this.eeBenefitAmounts = value;
    }

    /**
     * Gets the value of the spBenefitAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link SpBenefitAmounts }
     *     
     */
    public SpBenefitAmounts getSpBenefitAmounts() {
        return spBenefitAmounts;
    }

    /**
     * Sets the value of the spBenefitAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpBenefitAmounts }
     *     
     */
    public void setSpBenefitAmounts(SpBenefitAmounts value) {
        this.spBenefitAmounts = value;
    }

    /**
     * Gets the value of the tdiStatesBenefitAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link TdiStatesBenefitAmounts }
     *     
     */
    public TdiStatesBenefitAmounts getTdiStatesBenefitAmounts() {
        return tdiStatesBenefitAmounts;
    }

    /**
     * Sets the value of the tdiStatesBenefitAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TdiStatesBenefitAmounts }
     *     
     */
    public void setTdiStatesBenefitAmounts(TdiStatesBenefitAmounts value) {
        this.tdiStatesBenefitAmounts = value;
    }

    /**
     * Gets the value of the chIndividualPolicyBenefitAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link ChIndividualPolicyBenefitAmounts }
     *     
     */
    public ChIndividualPolicyBenefitAmounts getChIndividualPolicyBenefitAmounts() {
        return chIndividualPolicyBenefitAmounts;
    }

    /**
     * Sets the value of the chIndividualPolicyBenefitAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChIndividualPolicyBenefitAmounts }
     *     
     */
    public void setChIndividualPolicyBenefitAmounts(ChIndividualPolicyBenefitAmounts value) {
        this.chIndividualPolicyBenefitAmounts = value;
    }

    /**
     * Gets the value of the chBenefitAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link ChBenefitAmounts }
     *     
     */
    public ChBenefitAmounts getChBenefitAmounts() {
        return chBenefitAmounts;
    }

    /**
     * Sets the value of the chBenefitAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChBenefitAmounts }
     *     
     */
    public void setChBenefitAmounts(ChBenefitAmounts value) {
        this.chBenefitAmounts = value;
    }

    /**
     * Gets the value of the benefitAmountPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitAmountPercentage() {
        return benefitAmountPercentage;
    }

    /**
     * Sets the value of the benefitAmountPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitAmountPercentage(String value) {
        this.benefitAmountPercentage = value;
    }

    /**
     * Gets the value of the hundredPercentGuranteed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHundredPercentGuranteed() {
        return hundredPercentGuranteed;
    }

    /**
     * Sets the value of the hundredPercentGuranteed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHundredPercentGuranteed(String value) {
        this.hundredPercentGuranteed = value;
    }

    /**
     * Gets the value of the eligibleEmployeeGuaranteedIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibleEmployeeGuaranteedIssue() {
        return eligibleEmployeeGuaranteedIssue;
    }

    /**
     * Sets the value of the eligibleEmployeeGuaranteedIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibleEmployeeGuaranteedIssue(String value) {
        this.eligibleEmployeeGuaranteedIssue = value;
    }

    /**
     * Gets the value of the initialEnrollment property.
     * 
     * @return
     *     possible object is
     *     {@link InitialEnrollment }
     *     
     */
    public InitialEnrollment getInitialEnrollment() {
        return initialEnrollment;
    }

    /**
     * Sets the value of the initialEnrollment property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialEnrollment }
     *     
     */
    public void setInitialEnrollment(InitialEnrollment value) {
        this.initialEnrollment = value;
    }

    /**
     * Gets the value of the benefitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitType() {
        return benefitType;
    }

    /**
     * Sets the value of the benefitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitType(String value) {
        this.benefitType = value;
    }

    /**
     * Gets the value of the benefitPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitPeriod() {
        return benefitPeriod;
    }

    /**
     * Sets the value of the benefitPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitPeriod(String value) {
        this.benefitPeriod = value;
    }

    /**
     * Gets the value of the eliminationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEliminationPeriod() {
        return eliminationPeriod;
    }

    /**
     * Sets the value of the eliminationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEliminationPeriod(String value) {
        this.eliminationPeriod = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the optionalRider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalRider() {
        return optionalRider;
    }

    /**
     * Sets the value of the optionalRider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalRider(String value) {
        this.optionalRider = value;
    }

    /**
     * Gets the value of the progressiveRider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgressiveRider() {
        return progressiveRider;
    }

    /**
     * Sets the value of the progressiveRider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgressiveRider(String value) {
        this.progressiveRider = value;
    }

    /**
     * Gets the value of the tobacco property.
     * 
     * @return
     *     possible object is
     *     {@link Tobacco }
     *     
     */
    public Tobacco getTobacco() {
        return tobacco;
    }

    /**
     * Sets the value of the tobacco property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tobacco }
     *     
     */
    public void setTobacco(Tobacco value) {
        this.tobacco = value;
    }

    /**
     * Gets the value of the questions property.
     * 
     * @return
     *     possible object is
     *     {@link Questions }
     *     
     */
    public Questions getQuestions() {
    	if(questions == null) {
    		questions = new Questions();
    	}
        return questions;
    }

    /**
     * Sets the value of the questions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Questions }
     *     
     */
    public void setQuestions(Questions value) {
        this.questions = value;
    }

    /**
     * Gets the value of the affirmations property.
     * 
     * @return
     *     possible object is
     *     {@link Affirmations }
     *     
     */
    public Affirmations getAffirmations() {
    	if(affirmations == null) {
    		affirmations = new Affirmations();
    	}
        return affirmations;
    }

    /**
     * Sets the value of the affirmations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Affirmations }
     *     
     */
    public void setAffirmations(Affirmations value) {
        this.affirmations = value;
    }

    /**
     * Gets the value of the disclosures property.
     * 
     * @return
     *     possible object is
     *     {@link Disclosures }
     *     
     */
    public Disclosures getDisclosures() {
    	if(disclosures == null) {
    		disclosures = new Disclosures();
    	}
        return disclosures;
    }

    /**
     * Sets the value of the disclosures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Disclosures }
     *     
     */
    public void setDisclosures(Disclosures value) {
        this.disclosures = value;
    }

    /**
     * Gets the value of the healthQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link HealthQuestions }
     *     
     */
    public HealthQuestions getHealthQuestions() {
    	if(healthQuestions == null) {
    		healthQuestions = new HealthQuestions();
    	}
        return healthQuestions;
    }

    /**
     * Sets the value of the healthQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthQuestions }
     *     
     */
    public void setHealthQuestions(HealthQuestions value) {
        this.healthQuestions = value;
    }

    /**
     * Gets the value of the otherInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherInstructions() {
        return otherInstructions;
    }

    /**
     * Sets the value of the otherInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherInstructions(String value) {
        this.otherInstructions = value;
    }

    /**
     * Gets the value of the isChildCoverageOffered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsChildCoverageOffered() {
        return isChildCoverageOffered;
    }

    /**
     * Sets the value of the isChildCoverageOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsChildCoverageOffered(String value) {
        this.isChildCoverageOffered = value;
    }

    /**
     * Gets the value of the isChildTermlifeRiderOffered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsChildTermlifeRiderOffered() {
        return isChildTermlifeRiderOffered;
    }

    /**
     * Sets the value of the isChildTermlifeRiderOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsChildTermlifeRiderOffered(String value) {
        this.isChildTermlifeRiderOffered = value;
    }

    /**
     * Gets the value of the isUniqueIncrementsUtilized property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsUniqueIncrementsUtilized() {
        return isUniqueIncrementsUtilized;
    }

    /**
     * Sets the value of the isUniqueIncrementsUtilized property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsUniqueIncrementsUtilized(String value) {
        this.isUniqueIncrementsUtilized = value;
    }

    /**
     * Gets the value of the childCoverageOffered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildCoverageOffered() {
        return childCoverageOffered;
    }

    /**
     * Sets the value of the childCoverageOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildCoverageOffered(String value) {
        this.childCoverageOffered = value;
    }

    /**
     * Gets the value of the benefitAmountDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitAmountDescription() {
        return benefitAmountDescription;
    }

    /**
     * Sets the value of the benefitAmountDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitAmountDescription(String value) {
        this.benefitAmountDescription = value;
    }

    /**
     * Gets the value of the isProductAro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsProductAro() {
        return isProductAro;
    }

    /**
     * Sets the value of the isProductAro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsProductAro(String value) {
        this.isProductAro = value;
    }

}
