//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.28 at 06:46:14 PM IST 
//


package com.aflac.xml.casebuilder.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for caseBuilderForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="caseBuilderForm"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="groupNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="coverageEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="enrollmentRecord" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="enrollmentPlatform"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Ease"/&gt;
 *               &lt;enumeration value="Benetrac"/&gt;
 *               &lt;enumeration value="Selerix"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="accountInformation" type="{http://www.aflac.com/GroupMasterApplication}accountInformation"/&gt;
 *         &lt;element name="accident" type="{http://www.aflac.com/GroupMasterApplication}accident" minOccurs="0"/&gt;
 *         &lt;element name="hospitalIndemnity" type="{http://www.aflac.com/GroupMasterApplication}hospitalIndemnity" minOccurs="0"/&gt;
 *         &lt;element name="criticalIllness" type="{http://www.aflac.com/GroupMasterApplication}criticalIllness" minOccurs="0"/&gt;
 *         &lt;element name="benExtend" type="{http://www.aflac.com/GroupMasterApplication}benExtend" minOccurs="0"/&gt;
 *         &lt;element name="workSiteDisability" type="{http://www.aflac.com/GroupMasterApplication}workSiteDisability" minOccurs="0"/&gt;
 *         &lt;element name="wholeLife" type="{http://www.aflac.com/GroupMasterApplication}wholeLife" minOccurs="0"/&gt;
 *         &lt;element name="termLife" type="{http://www.aflac.com/GroupMasterApplication}termLife" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caseBuilderForm", propOrder = {
    "groupNo",
    "coverageEffectiveDate",
    "enrollmentRecord",
    "enrollmentPlatform",
    "accountInformation",
    "accident",
    "hospitalIndemnity",
    "criticalIllness",
    "benExtend",
    "workSiteDisability",
    "wholeLife",
    "termLife"
})
public class CaseBuilderForm {

    @XmlElement(required = true)
    protected String groupNo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected String coverageEffectiveDate;
    @XmlElement(required = true)
    protected String enrollmentRecord;
    @XmlElement(required = true)
    protected String enrollmentPlatform;
    @XmlElement(required = true)
    protected AccountInformation accountInformation;
    protected Accident accident;
    protected HospitalIndemnity hospitalIndemnity;
    protected CriticalIllness criticalIllness;
    protected BenExtend benExtend;
    protected WorkSiteDisability workSiteDisability;
    protected WholeLife wholeLife;
    protected TermLife termLife;

    /**
     * Gets the value of the groupNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * Sets the value of the groupNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupNo(String value) {
        this.groupNo = value;
    }

    /**
     * Gets the value of the coverageEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getCoverageEffectiveDate() {
        return coverageEffectiveDate;
    }

    /**
     * Sets the value of the coverageEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCoverageEffectiveDate(String value) {
        this.coverageEffectiveDate = value;
    }

    /**
     * Gets the value of the enrollmentRecord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentRecord() {
        return enrollmentRecord;
    }

    /**
     * Sets the value of the enrollmentRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentRecord(String value) {
        this.enrollmentRecord = value;
    }

    /**
     * Gets the value of the enrollmentPlatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentPlatform() {
        return enrollmentPlatform;
    }

    /**
     * Sets the value of the enrollmentPlatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentPlatform(String value) {
        this.enrollmentPlatform = value;
    }

    /**
     * Gets the value of the accountInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AccountInformation }
     *     
     */
    public AccountInformation getAccountInformation() {
        return accountInformation;
    }

    /**
     * Sets the value of the accountInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountInformation }
     *     
     */
    public void setAccountInformation(AccountInformation value) {
        this.accountInformation = value;
    }

    /**
     * Gets the value of the accident property.
     * 
     * @return
     *     possible object is
     *     {@link Accident }
     *     
     */
    public Accident getAccident() {
        return accident;
    }

    /**
     * Sets the value of the accident property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accident }
     *     
     */
    public void setAccident(Accident value) {
        this.accident = value;
    }

    /**
     * Gets the value of the hospitalIndemnity property.
     * 
     * @return
     *     possible object is
     *     {@link HospitalIndemnity }
     *     
     */
    public HospitalIndemnity getHospitalIndemnity() {
        return hospitalIndemnity;
    }

    /**
     * Sets the value of the hospitalIndemnity property.
     * 
     * @param value
     *     allowed object is
     *     {@link HospitalIndemnity }
     *     
     */
    public void setHospitalIndemnity(HospitalIndemnity value) {
        this.hospitalIndemnity = value;
    }

    /**
     * Gets the value of the criticalIllness property.
     * 
     * @return
     *     possible object is
     *     {@link CriticalIllness }
     *     
     */
    public CriticalIllness getCriticalIllness() {
        return criticalIllness;
    }

    /**
     * Sets the value of the criticalIllness property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriticalIllness }
     *     
     */
    public void setCriticalIllness(CriticalIllness value) {
        this.criticalIllness = value;
    }

    /**
     * Gets the value of the benExtend property.
     * 
     * @return
     *     possible object is
     *     {@link BenExtend }
     *     
     */
    public BenExtend getBenExtend() {
        return benExtend;
    }

    /**
     * Sets the value of the benExtend property.
     * 
     * @param value
     *     allowed object is
     *     {@link BenExtend }
     *     
     */
    public void setBenExtend(BenExtend value) {
        this.benExtend = value;
    }

    /**
     * Gets the value of the workSiteDisability property.
     * 
     * @return
     *     possible object is
     *     {@link WorkSiteDisability }
     *     
     */
    public WorkSiteDisability getWorkSiteDisability() {
        return workSiteDisability;
    }

    /**
     * Sets the value of the workSiteDisability property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkSiteDisability }
     *     
     */
    public void setWorkSiteDisability(WorkSiteDisability value) {
        this.workSiteDisability = value;
    }

    /**
     * Gets the value of the wholeLife property.
     * 
     * @return
     *     possible object is
     *     {@link WholeLife }
     *     
     */
    public WholeLife getWholeLife() {
        return wholeLife;
    }

    /**
     * Sets the value of the wholeLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link WholeLife }
     *     
     */
    public void setWholeLife(WholeLife value) {
        this.wholeLife = value;
    }

    /**
     * Gets the value of the termLife property.
     * 
     * @return
     *     possible object is
     *     {@link TermLife }
     *     
     */
    public TermLife getTermLife() {
        return termLife;
    }

    /**
     * Sets the value of the termLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermLife }
     *     
     */
    public void setTermLife(TermLife value) {
        this.termLife = value;
    }

}
