//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.28 at 06:46:14 PM IST 
//


package com.aflac.xml.casebuilder.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for case complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="case"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="planName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="planLevel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="series" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="coverageLevel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="applicationNumber" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="brochuresType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="taxType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hoursWorkedPerWeek" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="eligibilityWaitingPeriod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="employeeIssueAge" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="spouseIssueAge" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="childIssueAge" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="participationRequirement"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="hireDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="productRecord" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="healthQueReq" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "case", propOrder = {
    "planName",
    "planLevel",
    "series",
    "coverageLevel",
    "applicationNumber",
    "brochuresType",
    "taxType",
    "hoursWorkedPerWeek",
    "eligibilityWaitingPeriod",
    "employeeIssueAge",
    "spouseIssueAge",
    "childIssueAge",
    "participationRequirement",
    "hireDate",
    "productRecord",
    "healthQueReq"
})
public class Case {

    @XmlElement(required = true)
    protected String planName;
    @XmlElement(required = true)
    protected String planLevel;
    @XmlElement(required = true)
    protected String series;
    @XmlElement(required = true)
    protected String coverageLevel;
    protected String applicationNumber;
    @XmlElement(required = true)
    protected String brochuresType;
    @XmlElement(required = true)
    protected String taxType;
    @XmlElement(required = true)
    protected String hoursWorkedPerWeek;
    @XmlElement(required = true)
    protected String eligibilityWaitingPeriod;
    @XmlElement(required = true)
    protected String employeeIssueAge;
    @XmlElement(required = true)
    protected String spouseIssueAge;
    @XmlElement(required = true)
    protected String childIssueAge;
    @XmlElement(required = true)
    protected String participationRequirement;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar hireDate;
    @XmlElement(required = true)
    protected String productRecord;
    protected String healthQueReq;

    /**
     * Gets the value of the planName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * Sets the value of the planName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanName(String value) {
        this.planName = value;
    }

    /**
     * Gets the value of the planLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanLevel() {
        return planLevel;
    }

    /**
     * Sets the value of the planLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanLevel(String value) {
        this.planLevel = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeries() {
        return series;
    }

    /**
     * Sets the value of the series property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeries(String value) {
        this.series = value;
    }

    /**
     * Gets the value of the coverageLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageLevel() {
        return coverageLevel;
    }

    /**
     * Sets the value of the coverageLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageLevel(String value) {
        this.coverageLevel = value;
    }

    /**
     * Gets the value of the applicationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * Sets the value of the applicationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationNumber(String value) {
        this.applicationNumber = value;
    }

    /**
     * Gets the value of the brochuresType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrochuresType() {
        return brochuresType;
    }

    /**
     * Sets the value of the brochuresType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrochuresType(String value) {
        this.brochuresType = value;
    }

    /**
     * Gets the value of the taxType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxType() {
        return taxType;
    }

    /**
     * Sets the value of the taxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxType(String value) {
        this.taxType = value;
    }

    /**
     * Gets the value of the hoursWorkedPerWeek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoursWorkedPerWeek() {
        return hoursWorkedPerWeek;
    }

    /**
     * Sets the value of the hoursWorkedPerWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoursWorkedPerWeek(String value) {
        this.hoursWorkedPerWeek = value;
    }

    /**
     * Gets the value of the eligibilityWaitingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibilityWaitingPeriod() {
        return eligibilityWaitingPeriod;
    }

    /**
     * Sets the value of the eligibilityWaitingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibilityWaitingPeriod(String value) {
        this.eligibilityWaitingPeriod = value;
    }

    /**
     * Gets the value of the employeeIssueAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeIssueAge() {
        return employeeIssueAge;
    }

    /**
     * Sets the value of the employeeIssueAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeIssueAge(String value) {
        this.employeeIssueAge = value;
    }

    /**
     * Gets the value of the spouseIssueAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpouseIssueAge() {
        return spouseIssueAge;
    }

    /**
     * Sets the value of the spouseIssueAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpouseIssueAge(String value) {
        this.spouseIssueAge = value;
    }

    /**
     * Gets the value of the childIssueAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildIssueAge() {
        return childIssueAge;
    }

    /**
     * Sets the value of the childIssueAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildIssueAge(String value) {
        this.childIssueAge = value;
    }

    /**
     * Gets the value of the participationRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipationRequirement() {
        return participationRequirement;
    }

    /**
     * Sets the value of the participationRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipationRequirement(String value) {
        this.participationRequirement = value;
    }

    /**
     * Gets the value of the hireDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHireDate() {
        return hireDate;
    }

    /**
     * Sets the value of the hireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHireDate(XMLGregorianCalendar value) {
        this.hireDate = value;
    }

    /**
     * Gets the value of the productRecord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductRecord() {
        return productRecord;
    }

    /**
     * Sets the value of the productRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductRecord(String value) {
        this.productRecord = value;
    }

    /**
     * Gets the value of the healthQueReq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthQueReq() {
        return healthQueReq;
    }

    /**
     * Sets the value of the healthQueReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthQueReq(String value) {
        this.healthQueReq = value;
    }

}
