//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.28 at 06:46:14 PM IST 
//


package com.aflac.xml.casebuilder.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aflac.xml.casebuilder.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CaseBuilderForm_QNAME = new QName("http://www.aflac.com/GroupMasterApplication", "caseBuilderForm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aflac.xml.casebuilder.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CaseBuilderForm }
     * 
     */
    public CaseBuilderForm createCaseBuilderForm() {
        return new CaseBuilderForm();
    }

    /**
     * Create an instance of {@link Case }
     * 
     */
    public Case createCase() {
        return new Case();
    }

    /**
     * Create an instance of {@link Accident }
     * 
     */
    public Accident createAccident() {
        return new Accident();
    }

    /**
     * Create an instance of {@link CriticalIllness }
     * 
     */
    public CriticalIllness createCriticalIllness() {
        return new CriticalIllness();
    }

    /**
     * Create an instance of {@link HospitalIndemnity }
     * 
     */
    public HospitalIndemnity createHospitalIndemnity() {
        return new HospitalIndemnity();
    }

    /**
     * Create an instance of {@link BenExtend }
     * 
     */
    public BenExtend createBenExtend() {
        return new BenExtend();
    }

    /**
     * Create an instance of {@link WorkSiteDisability }
     * 
     */
    public WorkSiteDisability createWorkSiteDisability() {
        return new WorkSiteDisability();
    }

    /**
     * Create an instance of {@link TermLife }
     * 
     */
    public TermLife createTermLife() {
        return new TermLife();
    }

    /**
     * Create an instance of {@link WholeLife }
     * 
     */
    public WholeLife createWholeLife() {
        return new WholeLife();
    }

    /**
     * Create an instance of {@link AccountInformation }
     * 
     */
    public AccountInformation createAccountInformation() {
        return new AccountInformation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaseBuilderForm }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CaseBuilderForm }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.aflac.com/GroupMasterApplication", name = "caseBuilderForm")
    public JAXBElement<CaseBuilderForm> createCaseBuilderForm(CaseBuilderForm value) {
        return new JAXBElement<CaseBuilderForm>(_CaseBuilderForm_QNAME, CaseBuilderForm.class, null, value);
    }

}
