//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.28 at 06:46:14 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.aflac.com/GroupMasterApplication")
package com.aflac.xml.casebuilder.models;
