//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.29 at 12:02:24 PM IST 
//


package com.aflac.xml.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for generalRequirement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="generalRequirement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workingHoursPerWeek">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="startDate">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1st of the Month following"/>
 *               &lt;enumeration value="None"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numberOfPerUnit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="periodBasis">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Days"/>
 *               &lt;enumeration value="Weeks"/>
 *               &lt;enumeration value="Months"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="minimumEnrolledEmployee">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numberOfEligibleEmployee">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="otherRequirements">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generalRequirement", propOrder = {
    "workingHoursPerWeek",
    "startDate",
    "numberOfPerUnit",
    "periodBasis",
    "minimumEnrolledEmployee",
    "numberOfEligibleEmployee",
    "otherRequirements"
})
public class GeneralRequirement {

    protected int workingHoursPerWeek;
    @XmlElement(required = true)
    protected String startDate;
    @XmlElement(required = true)
    protected String numberOfPerUnit;
    @XmlElement(required = true)
    protected String periodBasis;
    protected int minimumEnrolledEmployee;
    protected int numberOfEligibleEmployee;
    @XmlElement(required = true)
    protected String otherRequirements;

    /**
     * Gets the value of the workingHoursPerWeek property.
     * 
     */
    public int getWorkingHoursPerWeek() {
        return workingHoursPerWeek;
    }

    /**
     * Sets the value of the workingHoursPerWeek property.
     * 
     */
    public void setWorkingHoursPerWeek(int value) {
        this.workingHoursPerWeek = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the numberOfPerUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfPerUnit() {
        return numberOfPerUnit;
    }

    /**
     * Sets the value of the numberOfPerUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfPerUnit(String value) {
        this.numberOfPerUnit = value;
    }

    /**
     * Gets the value of the periodBasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodBasis() {
        return periodBasis;
    }

    /**
     * Sets the value of the periodBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodBasis(String value) {
        this.periodBasis = value;
    }

    /**
     * Gets the value of the minimumEnrolledEmployee property.
     * 
     */
    public int getMinimumEnrolledEmployee() {
        return minimumEnrolledEmployee;
    }

    /**
     * Sets the value of the minimumEnrolledEmployee property.
     * 
     */
    public void setMinimumEnrolledEmployee(int value) {
        this.minimumEnrolledEmployee = value;
    }

    /**
     * Gets the value of the numberOfEligibleEmployee property.
     * 
     */
    public int getNumberOfEligibleEmployee() {
        return numberOfEligibleEmployee;
    }

    /**
     * Sets the value of the numberOfEligibleEmployee property.
     * 
     */
    public void setNumberOfEligibleEmployee(int value) {
        this.numberOfEligibleEmployee = value;
    }

    /**
     * Gets the value of the otherRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherRequirements() {
        return otherRequirements;
    }

    /**
     * Sets the value of the otherRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherRequirements(String value) {
        this.otherRequirements = value;
    }

}
