//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.29 at 12:02:24 PM IST 
//


package com.aflac.xml.models;

import java.time.LocalDate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for groupMasterData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="group-master-response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="groupProposalNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverageEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="situsState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="organizationName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="certificateHolder">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Employee"/>
 *               &lt;enumeration value="Associate"/>
 *               &lt;enumeration value="Member"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="policyHolders">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Employee"/>
 *               &lt;enumeration value="Union"/>
 *               &lt;enumeration value="value"/>
 *               &lt;enumeration value="PEO"/>
 *               &lt;enumeration value="Trust"/>
 *               &lt;enumeration value="MEWA"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="state">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="city">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="formID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="eligibleEesCount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="generalRequirement" type="{http://www.aflac.com/GroupMasterApplication}generalRequirement"/>
 *         &lt;element name="groupAccident" type="{http://www.aflac.com/GroupMasterApplication}groupAccident" minOccurs="0"/>
 *         &lt;element name="groupCriticalIllness" type="{http://www.aflac.com/GroupMasterApplication}groupCriticalIllness" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "group-master-response", propOrder = {
    "groupProposalNo",
    "coverageEffectiveDate",
    "situsState",
    "organizationName",
    "certificateHolder",
    "policyHolders",
    "state",
    "city",
    "formID",
    "eligibleEesCount",
    "generalRequirement",
    "groupAccident",
    "groupCriticalIllness"
})
public class GroupMasterData {

    @XmlElement(required = true)
    protected String groupProposalNo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar coverageEffectiveDate;
    @XmlElement(required = true)
    protected String situsState;
    @XmlElement(required = true)
    protected String organizationName;
    @XmlElement(required = true)
    protected String certificateHolder;
    @XmlElement(required = true)
    protected String policyHolders;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String formID;
    protected int eligibleEesCount;
    @XmlElement(required = true)
    protected GeneralRequirement generalRequirement;
    protected GroupAccident groupAccident;
    protected GroupCriticalIllness groupCriticalIllness;

    /**
     * Gets the value of the groupProposalNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupProposalNo() {
        return groupProposalNo;
    }

    /**
     * Sets the value of the groupProposalNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupProposalNo(String value) {
        this.groupProposalNo = value;
    }

    /**
     * Gets the value of the coverageEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCoverageEffectiveDate() {
        return coverageEffectiveDate;
    }

    /**
     * Sets the value of the coverageEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCoverageEffectiveDate(XMLGregorianCalendar value) {
        this.coverageEffectiveDate = value;
    }

    /**
     * Gets the value of the situsState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSitusState() {
        return situsState;
    }

    /**
     * Sets the value of the situsState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSitusState(String value) {
        this.situsState = value;
    }

    /**
     * Gets the value of the organizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * Sets the value of the organizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationName(String value) {
        this.organizationName = value;
    }

    /**
     * Gets the value of the certificateHolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateHolder() {
        return certificateHolder;
    }

    /**
     * Sets the value of the certificateHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateHolder(String value) {
        this.certificateHolder = value;
    }

    /**
     * Gets the value of the policyHolders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyHolders() {
        return policyHolders;
    }

    /**
     * Sets the value of the policyHolders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyHolders(String value) {
        this.policyHolders = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the formID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormID() {
        return formID;
    }

    /**
     * Sets the value of the formID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormID(String value) {
        this.formID = value;
    }

    /**
     * Gets the value of the eligibleEesCount property.
     * 
     */
    public int getEligibleEesCount() {
        return eligibleEesCount;
    }

    /**
     * Sets the value of the eligibleEesCount property.
     * 
     */
    public void setEligibleEesCount(int value) {
        this.eligibleEesCount = value;
    }

    /**
     * Gets the value of the generalRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralRequirement }
     *     
     */
    public GeneralRequirement getGeneralRequirement() {
        return generalRequirement;
    }

    /**
     * Sets the value of the generalRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralRequirement }
     *     
     */
    public void setGeneralRequirement(GeneralRequirement value) {
        this.generalRequirement = value;
    }

    /**
     * Gets the value of the groupAccident property.
     * 
     * @return
     *     possible object is
     *     {@link GroupAccident }
     *     
     */
    public GroupAccident getGroupAccident() {
        return groupAccident;
    }

    /**
     * Sets the value of the groupAccident property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupAccident }
     *     
     */
    public void setGroupAccident(GroupAccident value) {
        this.groupAccident = value;
    }

    /**
     * Gets the value of the groupCriticalIllness property.
     * 
     * @return
     *     possible object is
     *     {@link GroupCriticalIllness }
     *     
     */
    public GroupCriticalIllness getGroupCriticalIllness() {
        return groupCriticalIllness;
    }

    /**
     * Sets the value of the groupCriticalIllness property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupCriticalIllness }
     *     
     */
    public void setGroupCriticalIllness(GroupCriticalIllness value) {
        this.groupCriticalIllness = value;
    }

}
