//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.29 at 12:02:24 PM IST 
//


package com.aflac.xml.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="productName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rateGuaranteeLength">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="percentageByEmployee">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="percentageByEmployer">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="applicationType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="New Application"/>
 *               &lt;enumeration value="Change to Existing Aflac Policy"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="plan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nfo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Automatic Premium Loan"/>
 *               &lt;enumeration value="Extended Term Insurance"/>
 *               &lt;enumeration value="Reduced-Paid Up Insurance"/>
 *               &lt;enumeration value="Cash Surrender Value (CSV)"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="eliminationPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="benefitPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="policyInforce" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Yes"/>
 *               &lt;enumeration value="No"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="incomeReplacementPercentage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="other" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="aflacGroupNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="productProvisionCoverageType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="productSeries">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="productProvisionPortabilityType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="productCoverages" type="{http://www.aflac.com/GroupMasterApplication}productCoverages"/>
 *         &lt;element name="eligibilityReq" type="{http://www.aflac.com/GroupMasterApplication}eligibilityReq"/>
 *         &lt;element name="existingPolicy" type="{http://www.aflac.com/GroupMasterApplication}existingPolicy"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product", propOrder = {
    "productId",
    "productName",
    "rateGuaranteeLength",
    "percentageByEmployee",
    "percentageByEmployer",
    "applicationType",
    "plan",
    "clazz",
    "nfo",
    "eliminationPeriod",
    "benefitPeriod",
    "policyInforce",
    "incomeReplacementPercentage",
    "other",
    "aflacGroupNumber",
    "productProvisionCoverageType",
    "productSeries",
    "productProvisionPortabilityType",
    "productCoverages",
    "eligibilityReq",
    "existingPolicy"
})
public class Product {

    @XmlElement(required = true)
    protected String productId;
    @XmlElement(required = true)
    protected String productName;
    @XmlElement(required = true)
    protected String rateGuaranteeLength;
    protected int percentageByEmployee;
    protected int percentageByEmployer;
    @XmlElement(required = true)
    protected String applicationType;
    protected String plan;
    @XmlElement(name = "class")
    protected String clazz;
    protected String nfo;
    protected String eliminationPeriod;
    protected String benefitPeriod;
    protected String policyInforce;
    protected Integer incomeReplacementPercentage;
    protected String other;
    protected String aflacGroupNumber;
    @XmlElement(required = true)
    protected String productProvisionCoverageType;
    @XmlElement(required = true)
    protected String productSeries;
    @XmlElement(required = true)
    protected String productProvisionPortabilityType;
    @XmlElement(required = true)
    protected ProductCoverages productCoverages;
    @XmlElement(required = true)
    protected EligibilityReq eligibilityReq;
    @XmlElement(required = true)
    protected ExistingPolicy existingPolicy;

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the rateGuaranteeLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateGuaranteeLength() {
        return rateGuaranteeLength;
    }

    /**
     * Sets the value of the rateGuaranteeLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateGuaranteeLength(String value) {
        this.rateGuaranteeLength = value;
    }

    /**
     * Gets the value of the percentageByEmployee property.
     * 
     */
    public int getPercentageByEmployee() {
        return percentageByEmployee;
    }

    /**
     * Sets the value of the percentageByEmployee property.
     * 
     */
    public void setPercentageByEmployee(int value) {
        this.percentageByEmployee = value;
    }

    /**
     * Gets the value of the percentageByEmployer property.
     * 
     */
    public int getPercentageByEmployer() {
        return percentageByEmployer;
    }

    /**
     * Sets the value of the percentageByEmployer property.
     * 
     */
    public void setPercentageByEmployer(int value) {
        this.percentageByEmployer = value;
    }

    /**
     * Gets the value of the applicationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationType() {
        return applicationType;
    }

    /**
     * Sets the value of the applicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationType(String value) {
        this.applicationType = value;
    }

    /**
     * Gets the value of the plan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlan() {
        return plan;
    }

    /**
     * Sets the value of the plan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlan(String value) {
        this.plan = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the nfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNfo() {
        return nfo;
    }

    /**
     * Sets the value of the nfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNfo(String value) {
        this.nfo = value;
    }

    /**
     * Gets the value of the eliminationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEliminationPeriod() {
        return eliminationPeriod;
    }

    /**
     * Sets the value of the eliminationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEliminationPeriod(String value) {
        this.eliminationPeriod = value;
    }

    /**
     * Gets the value of the benefitPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitPeriod() {
        return benefitPeriod;
    }

    /**
     * Sets the value of the benefitPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitPeriod(String value) {
        this.benefitPeriod = value;
    }

    /**
     * Gets the value of the policyInforce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyInforce() {
        return policyInforce;
    }

    /**
     * Sets the value of the policyInforce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyInforce(String value) {
        this.policyInforce = value;
    }

    /**
     * Gets the value of the incomeReplacementPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIncomeReplacementPercentage() {
        return incomeReplacementPercentage;
    }

    /**
     * Sets the value of the incomeReplacementPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIncomeReplacementPercentage(Integer value) {
        this.incomeReplacementPercentage = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOther(String value) {
        this.other = value;
    }

    /**
     * Gets the value of the aflacGroupNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAflacGroupNumber() {
        return aflacGroupNumber;
    }

    /**
     * Sets the value of the aflacGroupNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAflacGroupNumber(String value) {
        this.aflacGroupNumber = value;
    }

    /**
     * Gets the value of the productProvisionCoverageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductProvisionCoverageType() {
        return productProvisionCoverageType;
    }

    /**
     * Sets the value of the productProvisionCoverageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductProvisionCoverageType(String value) {
        this.productProvisionCoverageType = value;
    }

    /**
     * Gets the value of the productSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductSeries() {
        return productSeries;
    }

    /**
     * Sets the value of the productSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSeries(String value) {
        this.productSeries = value;
    }

    /**
     * Gets the value of the productProvisionPortabilityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductProvisionPortabilityType() {
        return productProvisionPortabilityType;
    }

    /**
     * Sets the value of the productProvisionPortabilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductProvisionPortabilityType(String value) {
        this.productProvisionPortabilityType = value;
    }

    /**
     * Gets the value of the productCoverages property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCoverages }
     *     
     */
    public ProductCoverages getProductCoverages() {
        return productCoverages;
    }

    /**
     * Sets the value of the productCoverages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCoverages }
     *     
     */
    public void setProductCoverages(ProductCoverages value) {
        this.productCoverages = value;
    }

    /**
     * Gets the value of the eligibilityReq property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityReq }
     *     
     */
    public EligibilityReq getEligibilityReq() {
        return eligibilityReq;
    }

    /**
     * Sets the value of the eligibilityReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityReq }
     *     
     */
    public void setEligibilityReq(EligibilityReq value) {
        this.eligibilityReq = value;
    }

    /**
     * Gets the value of the existingPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link ExistingPolicy }
     *     
     */
    public ExistingPolicy getExistingPolicy() {
        return existingPolicy;
    }

    /**
     * Sets the value of the existingPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExistingPolicy }
     *     
     */
    public void setExistingPolicy(ExistingPolicy value) {
        this.existingPolicy = value;
    }

}
